version: "3.5"
volumes:
  mariadb:
    name: mariadb
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/$LOGIN/data/mariadb
  wordpress:
    name: wordpress
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/$LOGIN/data/wordpress

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    environment:
      - 
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
      
  